# Generated by Django 5.2.7 on 2025-10-19 13:13

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('booking_approved_agent', 'Booking Approved - To Agent'), ('booking_approved_client', 'Booking Approved - To Client'), ('booking_approved_salesman', 'Booking Approved - To Salesman'), ('booking_reminder_client', 'Booking Reminder - To Client'), ('booking_reminder_salesman', 'Booking Reminder - To Salesman'), ('ad_day_1', 'Attended Drip - Day 1'), ('ad_day_7', 'Attended Drip - Day 7'), ('ad_day_14', 'Attended Drip - Day 14'), ('ad_day_21', 'Attended Drip - Day 21'), ('dna_day_1', 'Did Not Attend Drip - Day 1'), ('dna_day_7', 'Did Not Attend Drip - Day 7'), ('dna_day_30', 'Did Not Attend Drip - Day 30'), ('dna_day_60', 'Did Not Attend Drip - Day 60'), ('dna_day_90', 'Did Not Attend Drip - Day 90')], max_length=50, unique=True)),
                ('email_subject', models.CharField(blank=True, max_length=200)),
                ('email_body', models.TextField(help_text='HTML email template. Available variables: {client_name}, {salesman_name}, {business_name}, {appointment_date}, {appointment_time}, {company_name}')),
                ('sms_body', models.TextField(help_text='SMS message (max 320 chars). Same variables as email.', max_length=320)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['message_type'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('plain_text_password', models.CharField(blank=True, max_length=255, null=True)),
                ('paypal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('bitcoin_wallet_address', models.CharField(blank=True, max_length=255, null=True)),
                ('ACH_bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ACH_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ACH_routing_number', models.CharField(blank=True, max_length=50, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active_salesman', models.BooleanField(default=False)),
                ('hire_date', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('password_reset_token', models.CharField(blank=True, max_length=100, null=True)),
                ('password_reset_sent_at', models.DateTimeField(blank=True, null=True)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('last_failed_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['start_date', 'end_date', 'is_active'], name='core_availa_start_d_062f57_idx')],
            },
        ),
        migrations.CreateModel(
            name='AvailableTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('appointment_type', models.CharField(choices=[('zoom', 'Zoom'), ('in_person', 'In-Person')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_booked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timeslots_created', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core.availabilitycycle')),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_timeslots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['salesman', 'date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(help_text='business name', max_length=200)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('appointment_type', models.CharField(choices=[('zoom', 'Zoom'), ('in_person', 'In-Person')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('no_show', 'No Show'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('meeting_address', models.CharField(blank=True, max_length=255)),
                ('zoom_link', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, help_text='State or City of salesman for in-person appointments', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='booking_audio/')),
                ('cancellation_reason', models.CharField(blank=True, choices=[('client_request', 'Client Requested Cancellation'), ('no_show', 'Client No-Show'), ('salesman_unavailable', 'Salesman Unavailable'), ('duplicate', 'Duplicate Booking'), ('other', 'Other')], max_length=50)),
                ('cancellation_notes', models.TextField(blank=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings_approved', to=settings.AUTH_USER_MODEL)),
                ('available_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='core.availabletimeslot')),
                ('canceled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings_canceled', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings_created', to=settings.AUTH_USER_MODEL)),
                ('declined_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings_declined', to=settings.AUTH_USER_MODEL)),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings_updated', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='core.client')),
            ],
            options={
                'ordering': ['appointment_date', 'appointment_time'],
            },
        ),
        migrations.CreateModel(
            name='DripCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_type', models.CharField(choices=[('attended', 'Attended (AD) - 21 Days'), ('did_not_attend', 'Did Not Attend (DNA) - 90 Days')], max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_stopped', models.BooleanField(default=False)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drip_campaigns', to='core.booking')),
                ('stopped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stopped_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('recipient_phone', models.CharField(blank=True, max_length=20)),
                ('communication_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='sent', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='core.booking')),
                ('message_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.messagetemplate')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('finalized', 'Finalized')], default='pending', max_length=20)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payrolls_finalized', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PayrollAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('bonus', 'Bonus'), ('penalty', 'Penalty'), ('correction', 'Correction'), ('cancellation_after_finalized', 'Cancellation After Finalized')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='core.booking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_adjustments', to=settings.AUTH_USER_MODEL)),
                ('payroll_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='core.payrollperiod')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='payroll_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='core.payrollperiod'),
        ),
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_phone', models.CharField(blank=True, max_length=20)),
                ('scheduled_for', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('drip_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='core.dripcampaign')),
                ('message_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.messagetemplate')),
            ],
            options={
                'ordering': ['scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Revenue Acceleration Unit', max_length=200)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('default_commission_rate_in_person', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10)),
                ('default_commission_rate_zoom', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=10)),
                ('buffer_time_minutes', models.IntegerField(default=30)),
                ('zoom_link', models.URLField(blank=True, default='https://us04web.zoom.us/j/77703295752?pwd=n8xdNGWmJa7mFnn1JlFwUw0C0jXNH0.1')),
                ('zoom_enabled', models.BooleanField(default=True, help_text='Enable/disable Zoom appointment bookings')),
                ('in_person_enabled', models.BooleanField(default=True, help_text='Enable/disable in-person appointment bookings')),
                ('reminder_lead_time_hours', models.IntegerField(default=24)),
                ('max_advance_booking_days', models.IntegerField(default=90)),
                ('min_advance_booking_hours', models.IntegerField(default=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('finalize', 'Finalize'), ('adjust', 'Adjust')], max_length=20)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.IntegerField()),
                ('changes', models.JSONField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='core_auditl_timesta_80074f_idx'), models.Index(fields=['user'], name='core_auditl_user_id_2ff9b7_idx'), models.Index(fields=['entity_type'], name='core_auditl_entity__246e0d_idx'), models.Index(fields=['entity_type', 'entity_id'], name='core_auditl_entity__244637_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='availabletimeslot',
            index=models.Index(fields=['salesman', 'date', 'appointment_type', 'is_active'], name='core_availa_salesma_2bf4aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='availabletimeslot',
            unique_together={('salesman', 'date', 'start_time', 'appointment_type')},
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['email'], name='core_client_email_9bd669_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['phone_number'], name='core_client_phone_n_dc5366_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['email', 'phone_number'], name='core_client_email_409963_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollperiod',
            index=models.Index(fields=['start_date'], name='core_payrol_start_d_d99060_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollperiod',
            index=models.Index(fields=['status'], name='core_payrol_status_508cd9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollperiod',
            unique_together={('start_date', 'end_date')},
        ),
        migrations.AddIndex(
            model_name='payrolladjustment',
            index=models.Index(fields=['payroll_period'], name='core_payrol_payroll_6d2023_idx'),
        ),
        migrations.AddIndex(
            model_name='payrolladjustment',
            index=models.Index(fields=['user'], name='core_payrol_user_id_63be77_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['appointment_date'], name='core_bookin_appoint_e75185_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['salesman'], name='core_bookin_salesma_c1cd86_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='core_bookin_status_fe12a1_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['salesman', 'appointment_date', 'status'], name='core_bookin_salesma_dc977c_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['payroll_period'], name='core_bookin_payroll_03737f_idx'),
        ),
    ]
