# Generated by Django 5.2.7 on 2025-10-15 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('booking_approved_agent', 'Booking Approved - To Agent'), ('booking_approved_client', 'Booking Approved - To Client'), ('booking_approved_salesman', 'Booking Approved - To Salesman'), ('booking_reminder_client', 'Booking Reminder - To Client'), ('booking_reminder_salesman', 'Booking Reminder - To Salesman'), ('ad_day_1', 'Attended Drip - Day 1'), ('ad_day_7', 'Attended Drip - Day 7'), ('ad_day_14', 'Attended Drip - Day 14'), ('ad_day_21', 'Attended Drip - Day 21'), ('dna_day_1', 'Did Not Attend Drip - Day 1'), ('dna_day_7', 'Did Not Attend Drip - Day 7'), ('dna_day_30', 'Did Not Attend Drip - Day 30'), ('dna_day_60', 'Did Not Attend Drip - Day 60'), ('dna_day_90', 'Did Not Attend Drip - Day 90')], max_length=50, unique=True)),
                ('email_subject', models.CharField(blank=True, max_length=200)),
                ('email_body', models.TextField(help_text='HTML email template. Available variables: {client_name}, {salesman_name}, {business_name}, {appointment_date}, {appointment_time}, {company_name}')),
                ('sms_body', models.TextField(help_text='SMS message (max 320 chars). Same variables as email.', max_length=320)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['message_type'],
            },
        ),
        migrations.CreateModel(
            name='DripCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_type', models.CharField(choices=[('attended', 'Attended (AD) - 21 Days'), ('did_not_attend', 'Did Not Attend (DNA) - 90 Days')], max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_stopped', models.BooleanField(default=False)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drip_campaigns', to='core.booking')),
                ('stopped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stopped_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('recipient_phone', models.CharField(blank=True, max_length=20)),
                ('communication_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='sent', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='core.booking')),
                ('message_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.messagetemplate')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_phone', models.CharField(blank=True, max_length=20)),
                ('scheduled_for', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('drip_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='core.dripcampaign')),
                ('message_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.messagetemplate')),
            ],
            options={
                'ordering': ['scheduled_for'],
            },
        ),
    ]
