# Generated by Django 5.2.7 on 2025-10-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hire_date',
            field=models.DateField(null=True),
        ),
    ]
