# Generated by Django 5.2.7 on 2025-10-09 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_booking_audio_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyHoliday',
        ),
    ]
