# Generated by Django 5.2.7 on 2025-10-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_booking_approved_at_booking_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabletimeslot',
            options={'ordering': ['salesman', 'date', 'start_time']},
        ),
        migrations.RemoveIndex(
            model_name='availabletimeslot',
            name='core_availa_salesma_a85a32_idx',
        ),
        migrations.RemoveField(
            model_name='availabletimeslot',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='availabletimeslot',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddIndex(
            model_name='availabletimeslot',
            index=models.Index(fields=['salesman', 'date', 'appointment_type', 'is_active'], name='core_availa_salesma_2bf4aa_idx'),
        ),
    ]
