# Generated by Django 5.2.7 on 2025-10-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_messagetemplate_dripcampaign_communicationlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ACH_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bitcoin_wallet_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='paypal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
