# Generated by Django 5.2.7 on 2025-10-09 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_companyholiday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabletimeslot',
            name='end_time',
        ),
    ]
