# Generated by Django 5.2.7 on 2025-10-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_ach_account_number_user_bitcoin_wallet_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='in_person_enabled',
            field=models.BooleanField(default=True, help_text='Enable/disable in-person appointment bookings'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='zoom_enabled',
            field=models.BooleanField(default=True, help_text='Enable/disable Zoom appointment bookings'),
        ),
    ]
