# Generated by Django 5.2.7 on 2025-10-05 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_employee_id_userpasswordlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPasswordLog',
        ),
    ]
