# Generated by Django 5.2.7 on 2025-10-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_systemconfig_in_person_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfig',
            name='zoom_link',
            field=models.URLField(blank=True, default='https://us04web.zoom.us/j/77703295752?pwd=n8xdNGWmJa7mFnn1JlFwUw0C0jXNH0.1'),
        ),
    ]
