# Generated by Django 5.2.7 on 2025-10-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_ach_bank_name_user_ach_routing_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='meeting_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
